### ISSUE TITLE
GDPR delete on Revoke

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#104]
When a user revokes a integration we need to delete all their data, to be GDPR compliant. We would like to make it a bit difficault for the user to accidentaly revoke a integration. [Here](https://www.loom.com/share/abcbe583ae404b18a5ed691f5f85360e?sid=2cc89af9-d187-4562-9fd4-fa94e7f18e68) is how github implemented deleting a repository. I don't think that we need to be that excaustive but using something the last screen should do the trick.

I'll enhance the excisting deAuthIntegration endpoint to delete the adAccount+ads+insights for that integration

**Comment by trixobird** [comment]
backend is done and deployed, I'll be removing myself and the `server` label from this issue.

**Comment by elevchyt** [comment]
Understandable, so we want the user's password to confirm deletion?

**Comment by trixobird** [comment]
No I think just a combination of these screen into once should suffice: 
<img width="477" alt="image" src="https://github.com/adsviewer/turboviewer/assets/12247364/97439c96-e8b7-4696-a14d-bc7a3faf9f8d">
<img width="476" alt="image" src="https://github.com/adsviewer/turboviewer/assets/12247364/77b614a5-9fa1-4c24-9d30-42049a925fe4">
Meaning we show a warning paragraph, then we force the user to type the word revoke and the the button revoke on the pop us is enabled.
Or something similar :)

**Comment by elevchyt** [comment]
Alright, sounds good.
