### ISSUE TITLE
orderBy absolute, add interval dropdown

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#124]
Right now we are ordering by spend | impressions | cpm relative to the last two intervals. We should have also the absolute values, meaning in the last interval which were these that performed best/worst in absolute terms

in addition to include the absolute values in order by, we need to have a drop down where the user can change intervals (montly and daily)

**Comment by dennislobster** [comment]
Hi guys, when can we expect this? I'd argue right now this is a large feature that's missing.

**Comment by trixobird** [comment]
we can prioritize it after the [invite flow](https://github.com/adsviewer/turboviewer/issues/302) and the [assign ad accounts for organization](https://github.com/adsviewer/turboviewer/issues/207) features are done. Would that be ok?
