### ISSUE TITLE
Confirm user email (unless they used google login)

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#132]
Users would first need to confirm their email (unless they use google login) and then split the flow.

Confirming the email flow:

1. user enters their details in the sign up page as they do now
2. on post backend send an email with a verification link- 
3. fronend intructs the user to login to their email and click on this link. It will have a resend email with a count down, the same way that we have handle forget password.
4. upon click backend change the user status to `CONFIRMED`, creates jwt and redirect the (logged in now) user to insights.
If the user has not confirmed the email, they won't be able to login, they will always stay in the screen on point 3.

Backend Flow:
Now if a user tries to sign up with user/pass it is signed in with all the usual JWT token attributes, but it has one more attribute: `userStatus: 'EMAIL_UNCONFIRMED'`.
When the backend sees a request with a token with such attribute the authScope is `emailUnconfirmed`. This scope has currently 2 endpoint that can hit (apart from the ones that require no authentication). The `me` and the `resendEmailConfirmation`. 
Therefore when the user is logged in a special page needs to be created that would ask the user to go to their email client and click the link to verify their email.

Upon clicking that email the user is directed to the backend that will check the token, its expiration date and if everything is allright it will update the user status to EMAIL_CONFIRMED, generate the jwts and return to `${env.PUBLIC_URL}/api/auth/sign-in?token=${response.token}&refreshToken=${response.refreshToken}` that immediately saves these jwts and then the middleware.ts redirects the user to the insights page. 
Therefore **almost** no action is required from the frontend in this case.

The almost clause refers to error handling. If the backend for any reason fails to update the user (tampered url, expired token, or some other unknown error), it currently redirects the user to `${env.PUBLIC_URL}?error=_error message_`. Currently no error is shown to the user.

**Comment by elevchyt** [comment]
Nice, I'd like to have the user status exposed to the FE so that I can use them, too if possible 🐤 

Also, isn't using a link + hash with the user id to confirm better, since in your implementation the user is required to be logged in with an UNCONFIRMED_EMAIL user status in their JWT token?

**Comment by trixobird** [comment]
> Nice, I'd like to have the user status exposed to the FE so that I can use them, too if possible 🐤

done :) sorry for missing it

> Also, isn't using a link + hash with the user id to confirm better, since in your implementation the user is required to be logged in with an UNCONFIRMED_EMAIL user status in their JWT token?

hmmm I think that is exactly what I am doing. [Here](https://github.com/adsviewer/turboviewer/blob/107c0b5f10aea2b13d5273cc01524a7ac77666eb/apps/server/src/contexts/user.ts#L204-L236) BE creates a tocken as a query parameter. If the user clicks on that link then [here](https://github.com/adsviewer/turboviewer/blob/107c0b5f10aea2b13d5273cc01524a7ac77666eb/apps/server/src/contexts/user.ts#L146-L161) the BE confirms the user after checking the token.

The endpoint that are available for user are in case the user tries to access our website withough being confirmed.

Happy to talk over this, I think I am missing something.
