### ISSUE TITLE
P2: Add data_last_fetched to integrations screen

### ISSUE THREAD

**Issue by dennislobster** [adsviewer/turboviewer#152]
In the integrations screen, for every datasource add:

- [ ] how long ago data was fetched (i.e. 6 hrs ago)
- [ ] how large the total dataset is (i.e. 1000 advertisements) -> calculate as distinct count

### Backend Integration done

Now integrations endpoint can be filtered also by status. Additionally it retuns lastSyncedAt and in the AdAccount we have adCount

example query
```
query integrations {
  integrations {
    lastSyncedAt
    adAccounts {
      adCount
    }
  }
}
```

**Comment by trixobird** [comment]
@dennislobster, let's say that an integration has this break down:
- adAccountA
  - adA with 10 insights
  - adB with 20 insights
- adAccountB
  - adC with 30 insights

What would be the number to show? Keep in mind that this answer maybe different(?) for agency and the underlying company

**Comment by dennislobster** [comment]
Good question @trixobird - 

It should always show the distinct number of ad_ids for a given integration (across ad accounts the organization has access to).

So if multiple accounts, maybe show: (or roll into 1 number)
Account X: 120 ads
Account Y: 50 ads
Account ...
