### ISSUE TITLE
Neighbor components re-rendering each other

### ISSUE THREAD

**Issue by elevchyt** [adsviewer/turboviewer#200]
The issue arises when some state changes inside the settings button component and its child components.
You can tell this is happening because when that state is changed, it re-renders the page.tsx of the insights page which performs a new request to fetch insights (can be seen in the front end since insights fade in again when opening the settings modal and even when changing language or color scheme).

**Comment by trixobird** [comment]
I am a bit unclear on which of the two bugs this issues will solve. The one is the flicker that the #176 introduced and the other is the settings on the top right causing an unncessery invocation of insights endpoint
