### ISSUE TITLE
members management

### ISSUE THREAD

**Issue by elevchyt** [adsviewer/turboviewer#302]
The FE part of the following issues:
https://github.com/adsviewer/turboviewer/issues/137
https://github.com/adsviewer/turboviewer/issues/138
https://github.com/adsviewer/turboviewer/issues/186

**Comment by trixobird** [comment]
renamed token to invite_hash. I create a [label](https://github.com/adsviewer/turboviewer/blob/d436550d3be88deeed1ba60969c984e0498325c1/packages/shared-types/src/index.ts#L12) that you may use
