### ISSUE TITLE
deploy landing-page

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#326]
Dennis finished the content of the landing page. @elevchyt it is up to you to make it up to our standards. 

In addition to this here are some comments/requests:

- [x] Integration section is not aligned
- [x] Brands should be centred
- [x] Brand images are not the correct ratio
- [x] In integrations let’s split meta to fb and instagram. Also add a YouTube(!) icon as well.
- [x] Contact us in scale pricing (tier 4) should point to the contact form
- [x] T&C should be migrated from [here](https://github.com/adsviewer/adsviewer/blob/3dd365492794473070831d611dcfbc6393f6d12c/assets/static/terms.html#L19)
- [x] Our Logo dark needs to change (looks small)
- [x] Maybe we can do something for “The Alpha Men” on the dark mode

I'll create sepearte issues for newletter, stripe and contect form endpoints

**Comment by trixobird** [comment]
> Good work @dennis-adsviewer! One suggestion is that we should probably use the app's blue color (#2271C2) instead of the one in the landing page (#136CFE).
> 
> Other than that, great job! I'm taking a look on the issues right now :)

Feel free to change the color, you are the boss on the UI :)

**Comment by trixobird** [comment]
> This is probably a leftover and I should remove it, right?
> 
> ![Image](https://private-user-images.githubusercontent.com/50188474/363184459-299e0269-e885-40b1-a327-4729107cb9ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjM4NjUsIm5iZiI6MTcyNTAyMzU2NSwicGF0aCI6Ii81MDE4ODQ3NC8zNjMxODQ0NTktMjk5ZTAyNjktZTg4NS00MGIxLWEzMjctNDcyOTEwN2NiOWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEzMTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OWNlNjkwODg1YTZmNDUxMGIyNTQwNzYyNzBhZTJiZWEyOTM5ZjdkOTkyNTZkZmU3N2Y5NzczN2U1MWY2OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZtFF05iNfo5QdeO2uvgqVp0vKzn5r5pLCmSQqRNznRE)

This was my initial reaction as well, but it is not, there are the descriptions of the tiers. I also don't like its UI, maybe you can do something about it?

**Comment by dennis-adsviewer** [comment]
Yeah, we can rebuild it, maybe to be more like something like this:
https://otter.ai/pricing

i can help with the content, just don't know how to handle all the css fully...

**Comment by elevchyt** [comment]
> Yeah, we can rebuild it, maybe to be more like something like this: https://otter.ai/pricing
> 
> i can help with the content, just don't know how to handle all the css fully...
> 
> Additionally, @elevchyt for now please remove FAIRE & The alpha men logo - we can add them soon after signing some documents.

Sounds good, you can check out the change I've done on the pricing, just pull the changes from this branch.
I think it's much better now, but moving forward I can look into doing something similar to otter.ai :)
