### ISSUE TITLE
Invited User can create organization after being removed.

### ISSUE THREAD

**Issue by dennislobster** [adsviewer/turboviewer#344]
I was able to invite dennis.kreeft@faire.com to my org (parent: dennis.kreeft@hotmail.com) and did the following:
- removed user (...faire.com) from organization menu
- create new organization (was not force logged out)

**Comment by trixobird** [comment]
We are using JWT for authorization/authentication. This means when we remove a user from an org, the user's token is intact, therefore they will have all the access that they used to have. This will last [5'](https://github.com/adsviewer/turboviewer/blob/f013ea21f1b73617533ce9785903865f32cd5bd3/apps/server/src/auth.ts#L12) at most, this token will expire and after the refresh they won't have access to that org any more.
