### ISSUE TITLE
cpm could be null (if impressions are 0)

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#366]
If impressions are 0, then cpm is divided by zero. I decided to make it null, instead of 0, or infinite (happy to be challenged on this)

I made some quick fixes, as shown [here](https://github.com/adsviewer/turboviewer/pull/365/files#diff-e7de96a71cdc2628e1285c27b1a5c2d459d5f78f123aef50e001ecb9ce4c5e51), but I am openinig this ticket to track any improvements that we want to make. 

May the correct approach is not to show cpm at all when is null instead of zero.

Another thing that I noted is that the `setupRank` is computed with cpm. Wouldn't it be better to be computed by the datapoint that the user sorted by?

**Comment by elevchyt** [comment]
`Another thing that I noted is that the setupRank is computed with cpm. Wouldn't it be better to be computed by the datapoint that the user sorted by?`

Maybe @dennis-adsviewer could tell us what he thinks about this :)
