### ISSUE TITLE
cannot accept cookies

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#405]
Users that are not using the integrated channel will be presented with the usuall accept cookies pop up in the ads preview.

How to reproduce: Delete facebook.com cookies from localhost and reload.

**Comment by elevchyt** [comment]
Will try to set iframes to 380x814 if we don't have Meta cookies saved locally.

**Comment by trixobird** [comment]
I think solving it in the BE is not a good idea. I will have to parse the htlm for every single iFrame, that does not make sense. I think the last resort is for the FE to see if they can "sense" (without doing any heave duty work) what is rendered inside the iFrame and if they observer cookies then we re-render with the hard coded dimensions. What say oyou @elevchyt ?

**Comment by trixobird** [comment]
This is too much hussle to fix
