### ISSUE TITLE
Sub Organizations should not be able to create new sub-sub organizations

### ISSUE THREAD

**Issue by dennis-adsviewer** [adsviewer/turboviewer#444]
If Organization is 0, we should only allow 0 -> N sub organizations, right now I can freely create infinite sub-sub-sub-sub organizations.

Example for a user (Coen) who manages multiple clients;
Main Organization: Coen's org.
Sub organizations: Client 1, Client 2, Client 3, etc.

Client 1, Client 2, Client 3 should not have ability to create sub organizations.

**Comment by trixobird** [comment]
We can certainly pose this restriction, what about this scenario: Versuni assigns all Philips accountds to a Philips organization. Then Philips wants to create sub organizations to separate these accounts (e.g. by country)

**Comment by dennis-adsviewer** [comment]
I don't see this scenario happening quickly for now - I think right now the restriction makes sense because otherwise it can be confusing if a user creates a sub sub organization and gets lost in the process.

**Comment by trixobird** [comment]
@elevchyt I am not allowing the creation of a sub sub organization. We need to do the same on the front end (disable the + sumbol I assume). You already should have the info whether an organization is root or not
