### ISSUE TITLE
Replace account button on integrations with other button

### ISSUE THREAD

**Issue by dennis-adsviewer** [adsviewer/turboviewer#445]
Right now the 'Ad' button to select specific accounts is not intuitive within integrations.

Instead we should add a new button per integration which is under Reconnect & Revoke, called: 'Select Account(s)'.

**Comment by elevchyt** [comment]
@dennis-adsviewer Shouldn't revoke be last from a UX perspective?
Maybe we could have 'Select Account(s)' on top, over reconnect.

**Comment by dennis-adsviewer** [comment]
Sure, on top makes most sense indeed, just make sure it says Select instead of View. Aside from that LGTM
