### ISSUE TITLE
Sub organization - include existing organization users

### ISSUE THREAD

**Issue by dennis-adsviewer** [adsviewer/turboviewer#446]
When creating a new sub-organization, we should ask the user if they want to include / exclude existing users from that sub-organization.

Right now, Raghu would need to manually reinvite specific users (which have access to the whole org) to any sub-organization he creates.

**Comment by trixobird** [comment]
I think the best solution is a pop up with all the users of the parent org and the creators chooses which ones want to have access to the new org as well, also also with what *role*

**Comment by trixobird** [comment]
@elevchyt what do you think?

**Comment by trixobird** [comment]
Lefteri, I added `users` in the `createOrganization` endpoint
