### ISSUE TITLE
integration ad count not taking into account only included ad accounts

### ISSUE THREAD

**Issue by elevchyt** [adsviewer/turboviewer#462]
Ad count should show only the included ad accounts' summed ad count, but instead shows the sum of every ad account.
(In this example the ad count should be 76 since 1 ad account with 76 ads is selected.

![image](https://github.com/user-attachments/assets/2f9c47a6-e5af-4ecb-bb78-1f285eefdb01)

![image](https://github.com/user-attachments/assets/8fdc7d89-7681-40f4-80f8-3ccf6bbcb2e0)

**Comment by trixobird** [comment]
it seems that it works on my machine (TM) :P https://www.loom.com/share/f0b1da41a5a74cc0a1a4228b296b3ea7?sid=4dc93be8-f863-4add-912e-69661e75b83d Let's hudle to see what I am missing

**Comment by elevchyt** [comment]
> it seems that it works on my machine (TM) :P https://www.loom.com/share/f0b1da41a5a74cc0a1a4228b296b3ea7?sid=4dc93be8-f863-4add-912e-69661e75b83d Let's hudle to see what I am missing

Probably corrupted data on my end.
