### ISSUE TITLE
server validation errors in insights are not surfacing in the FE

### ISSUE THREAD

**Issue by trixobird** [adsviewer/turboviewer#469]
In insights there are a couple of validation (one that the FE is not checking for example is if the interval is days, the max date interval is 90 days). The FE is not surfacing these errors, there are 500 errors in the network tab

**Comment by elevchyt** [comment]
Looks like the FE isn't handling these errors due to them being in a different format than the graphql result format.
Still, the FE needs some changes to handle these errors once the response changes to the typical urql result.
