### ISSUE TITLE
Improved onboarding flow

### ISSUE THREAD

**Issue by dennislobster** [adsviewer/turboviewer#524]
After a user signs up they will land on the Insights page which is empty. We should improve this to make it more natural to add integrations and get data going.

Something like this:
![Section 1](https://github.com/user-attachments/assets/9427e00a-e438-42b2-81f3-b8e804b23f06)

I will provide the video.

**Comment by elevchyt** [comment]
I like this, are the **Integrations** and **Organization** badges at the bottom of the card buttons that navigate to the corresponding pages or do they server another purpose?

**Comment by dennis-adsviewer** [comment]
Yes, buttons for navigation

**Comment by elevchyt** [comment]
Great, and do we want the video to play in a pop-up (like a lightbox) or on the view (meaning replacing the card with a large video player and playing the video)?

**Comment by dennis-adsviewer** [comment]
Not sure, but I trust in your choice for what will look best for the end user!
