### ISSUE TITLE
Improved 'Summary' view

### ISSUE THREAD

**Issue by dennislobster** [adsviewer/turboviewer#525]
Our current insights view is overwhelming for users, I would like to add a higher level summary view which shows high level data + top ads per integration with opportunity to get more detailed view.

**Example figma:**
![Section 1 (1)](https://github.com/user-attachments/assets/2cd39367-b7ae-4c92-ae19-27862488f845)

I would like this view to read like you are opening the front page of a newspaper and reading about your advertisements and creative information, and be used as a central hub for the tool to give insights. (for example things like: ad x got Y more impressions vs. last week, ad Z is new on platform Tiktok, AI analysis completed for ad XYZ etc)

**Comment by elevchyt** [comment]
This is pretty good, definitely needs work on the backend, too for determining top performing ads, summary chart datapoints etc.
If both of these are too much work, then this issue can be split in 2 different issues.
What do you think? @trixobird

**Comment by elevchyt** [comment]
@dennislobster Couple of questions after we discussed with @trixobird.
1. Is this whole page one view? (because there is the sidebar for each feature) 
2. I assume by "per publisher" you mean "per integration/channel", right?
3. What are the criteria that determine the top ads? Also, are the top ads for the selected publisher/channel (whatever it is from question 1) or for EVERY publisher.
4. Should the date on the top right be a datepicker, since under the chart you mention PERIOD so I assume that users should be able to have total control of the selected date range.

**Comment by dennis-adsviewer** [comment]
1. Yes it should be a scrolling view. I want that to be called 'summary view', the view we currently have should be called detail. And then there will also be a creative comparison tab (which we need to scope, and build as a new feature)
2. Yes by integration/channel, for example: Tiktok, Facebook, Instagram, LinkedIn, YouTube should be seperate lines. But a user should maybe also be able to select themselves in the future.
3. Top ads should be determined by a drop down selector, right now based on: spend, impressions or cpm, but in the future a user needs to be able to select a custom logic. The top ads should be PER publisher, so if a user is integrated with Facebook, LinkedIn and Tiktok it should be 3 seperate blocks, 1 per publisher. Ideally we make the view a horizontal 'infinity scroll', so a user can just keep clicking further and further (not necessary for now)
4. It should be a date picker, standard selection should be last 28 days

**Comment by trixobird** [comment]
regarding 2,3 publisher is different than channel. Channels are meta, linkedIn, tiktok while publishers are 
  Facebook
  Instagram
  Messenger
  AudienceNetwork
  LinkedIn
  TikTok
  GlobalAppBundle
  Pangle

So will it be channel or publisher? (the answer may differ for 2 and 3

**Comment by dennis-adsviewer** [comment]
Ok, for:
2. Publisher
3. per Channel
