### ISSUE TITLE
User feedback functionality

### ISSUE THREAD

**Issue by elevchyt** [adsviewer/turboviewer#543]
A feedback button should be implemented so that users can provide useful feedback and/or bug reports.
There should be a relation in the DB between the user and the feedback entry, a **feedback type** field with the values: "Bug Report", "Feature Suggestion" and "Other", and also another field for the feedback's **message body**.

Ideally, the users should receive an email informing them that their feedback was submitted successfully.

**Comment by trixobird** [comment]
should we close this @aaryansinha16 , @elevchyt ?
