### ISSUE TITLE
'Save' advanced search strings as custom 'pre-loads'

### ISSUE THREAD

**Issue by dennis-adsviewer** [adsviewer/turboviewer#565]
All clients have requested functionality to be able to save filters in one way or another. Two main requests have emerged:
1. Save filter as a preset, to be able to quickly reload
   - For example Versuni might want to save a filter which searches for 'campaign_name' contains 'baristina'
        -  they want to be able to save the filter with a specific Name, for example: Baristina

2. Save filter as a custom 'tag' / dimension, to be able to select as a grouping variable in the querybuilder or in charts.
    - Example use case(s): 
       - Versuni wants to combine TikTok and Meta into a specific new grouping, and analyse that performance at a high level vs. Google or another platform
       - Versuni wants to group all ads with a specific creative element (like description) into a sub group, and add this as a filter dropdown on the ribbon on the left
       
I understand Option 1 will be much easier to accomplish than option 2. Maybe we break this into two separate branches and tackle no.1 first.

**Comment by dennis-adsviewer** [comment]
@elevchyt for no.1 do you need backend help?

**Comment by elevchyt** [comment]
> @elevchyt for no.1 do you need backend help?

Yes, 1 definitely needs backend work to be able to save & fetch these search presets/filters. Might be a good task for @aaryansinha16.

2 is kind of hard for me to understand... From what I can tell, it's unrelated to the search, and is instead a way for users to have custom groupings?

**Comment by dennislobster** [comment]
Hi, when will we finish # 1 here? Versuni is asking specifically for it. 
The filters should be at the organization level, and users should be able to create them from within the advanced search functionality / name them.

For now, let's not focus on user groups, just move quickly to get more feedback :)
