### ISSUE TITLE
User bug: stuck on 'introduction'

### ISSUE THREAD

**Issue by dennis-adsviewer** [adsviewer/turboviewer#721]
Someone at Faire is encountering an issue where they get pushed to /introduction view, even though they have proper access.

Is this a bug related to onboarding flow / state?

username: Emiri Sakurai

![adsviewerbug-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/ead72c42-d6fb-44da-bb76-fbcc0721f3ed)

**Comment by trixobird** [comment]
fixed through #722
